stack_size_error_text = 'stack size parameter should be integer type'
stack_size_zero_warn = 'Size of stack is zero, still want to continue? '
stack_safe_mode_flag_error = 'safe_mode flag can only be True or False'
push_element_is_none = 'Please insert a not None element'
stack_resize_option_error = 'Invalid resize_option, it should be either + or -'